# Generated by Django 4.2.3 on 2023-07-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_haven_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.CharField(),
        ),
    ]
